// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	users "messaging/business/users"

	mock "github.com/stretchr/testify/mock"
)

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: username
func (_m *Services) GetUser(username string) (*users.Users, error) {
	ret := _m.Called(username)

	var r0 *users.Users
	if rf, ok := ret.Get(0).(func(string) *users.Users); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.Users)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistersNewUser provides a mock function with given fields: _a0
func (_m *Services) RegistersNewUser(_a0 *users.UsersSpec) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*users.UsersSpec) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
